// src/components/header/Header.tsx
import React from 'react';
import { useTranslation } from 'react-i18next';

function Header(): React.ReactElement {
  const { i18n } = useTranslation();

  const handleLanguageChange = (value: typeof i18n.language) => {
    i18n.changeLanguage(value);
  };

  return (
    <div className="header__box">
      <p>当前语言: {i18n.language}</p>
      <button onClick={() => handleLanguageChange('zh-CN')}>简体中文</button>
      <button onClick={() => handleLanguageChange('zh-TW')}>繁体中文</button>
      <button onClick={() => handleLanguageChange('en-US')}>英文</button>
    </div>
  );
}

export default Header;

// app/components/header/index.vue
<template>
  <div class="header__box">
    <p>当前语言: {{ locale }}</p>
    <button @click="handleLocaleChange('zh-CN')">简体中文</button>
    <button @click="handleLocaleChange('zh-TW')">繁體中文</button>
    <button @click="handleLocaleChange('en-US')">English</button>
  </div>
</template>

<script setup lang="ts">
const { locale, setLocale } = useI18n();

const handleLocaleChange = (value: typeof locale.value) => {
  setLocale(value);
};
</script>

<style scoped lang="scss"></style>
