// src/app/about/page.tsx
import React from 'react';
import Link from 'next/link';
import styles from './page.module.css';

async function About(props: PageProps<'/about'>): Promise<React.ReactElement> {
  const params = await props.params;
  const searchParams = await props.searchParams;

  // 获取路由参数, 例如 /about/:id, 可以通过 params.id 获取
  // 获取查询参数, 例如 /about?id=123, 可以通过 searchParams.id 获取
  console.log('Params:', params);
  console.log('Search Params:', searchParams);

  return (
    <div className={styles.page}>
      <p>About Page</p>
      <Link href="/">Jump To Home Page</Link>
      <Link href="/i18n">Jump To I18n Page</Link>
    </div>
  );
}

export default About;

// app/pages/about/index.vue
<template>
  <div class="about">
    <p>About Page</p>
    <NuxtLink to="/">Jump To Home Page</NuxtLink>
    <NuxtLink to="/i18n">Jump To I18n Page</NuxtLink>
  </div>
</template>

<script setup lang="ts">
const route = useRoute();

// 获取路由参数, 例如 /about/:id, 可以通过 route.params.id 获取
// 获取查询参数, 例如 /about?id=123, 可以通过 route.query.id 获取
console.log('Params:', route.params);
console.log('Search Params:', route.query);
</script>

<style lang="scss" scoped></style>
