// src/components/layout/Layout.tsx
import React from 'react';
import { Outlet } from 'react-router';
import Header from '@/components/header/Header';
import Footer from '@/components/footer/Footer';

function Layout(): React.ReactElement {
  return (
    <>
      <Header />
      <Outlet />
      <Footer />
    </>
  );
}

export default Layout;

// src/components/layout/index.vue
<template>
  <Header />
  <router-view v-slot="{ Component }">
    <component v-if="!$route.meta.keepAlive" :is="Component" />
    <keep-alive>
      <component v-if="$route.meta.keepAlive" :is="Component" />
    </keep-alive>
  </router-view>
  <Footer />
</template>

<script setup lang="ts">
import Header from '@/components/header/index.vue';
import Footer from '@/components/footer/index.vue';
</script>
