// src/views/home/Home.tsx
import React, { Suspense } from 'react';
import { Link, useLoaderData, Await } from 'react-router';
import { login } from '@/api/user';
import type { ResponseType } from '@/types';

export async function loader() {
  const loaderPromise = login({ account: 'xlz122', password: '123456' });
  return { loaderPromise };
}

function Home(): React.ReactElement {
  const { loaderPromise } = useLoaderData<typeof loader>();

  const RenderContent = ({ response }: { response: ResponseType<{ token: string }> }) => (
    <>
      <p>{response.code}</p>
      <p>{response.data.token}</p>
      <p>{response.message}</p>
    </>
  );

  return (
    <div className="home">
      <p>Home Page</p>
      <Link to="/about">Jump To About Page</Link>
      <Link to="/i18n">Jump To I18n Page</Link>

      <Suspense fallback={<div>Loading...</div>}>
        <Await
          resolve={loaderPromise}
          children={(response) => <RenderContent response={response} />}
          errorElement={<p>Error!</p>}
        />
      </Suspense>
    </div>
  );
}

export default Home;

// src/views/home/index.vue
<template>
  <div class="home">
    <p>Home Page</p>
    <router-link to="/about">Jump To About Page</router-link>
    <router-link to="/i18n">Jump To I18n Page</router-link>
  </div>
</template>

<script setup lang="ts">
import { ref } from 'vue';
import { login } from '@/api/user';
import type { ResponseType } from '@/types';

const response = ref({});

const getResponse = async () => {
  const res: ResponseType = await login({ account: 'xlz122', password: '123456' });
  if (res?.code !== 200) {
    return;
  }

  response.value = res.data ?? {};
};
getResponse();
</script>

<style lang="scss" scoped></style>
